#!/usr/bin/env node
/**
 * lang-cli — locale tooling for XCoder.
 *
 *   node utils/lang-cli.mjs                 # generate missing locale stubs (43 locales)
 *   node utils/lang-cli.mjs --check         # verify en/pt/es key parity
 *   node utils/lang-cli.mjs --missing pt    # list keys missing from a locale
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const LANG_DIR = join(ROOT, 'src', 'lang');
const GEN_DIR = join(LANG_DIR, 'gen');

const ALL_LOCALES = [
  'af', 'ar', 'bn', 'cs', 'da', 'de', 'el', 'en', 'es', 'fa', 'fi', 'fr', 'he', 'hi',
  'hu', 'id', 'it', 'ja', 'ko', 'ms', 'nl', 'no', 'pl', 'pt', 'pt-BR', 'ro', 'ru',
  'sk', 'sr', 'sv', 'th', 'tr', 'uk', 'ur', 'vi', 'zh', 'zh-TW', 'bg', 'ta', 'te',
  'ml', 'km', 'ne',
];

function parseKeys(source) {
  const keys = new Set();
  const re = /'([\w.]+)':/g;
  let m;
  while ((m = re.exec(source))) keys.add(m[1]);
  return keys;
}

function enSource() {
  return readFileSync(join(LANG_DIR, 'en.ts'), 'utf8');
}

function localeKeys(file) {
  return parseKeys(readFileSync(file, 'utf8'));
}

function ensureGenStubs() {
  mkdirSync(GEN_DIR, { recursive: true });
  const en = enSource();
  const keyCount = parseKeys(en).size;
  const generatedCodes = [];
  let created = 0;
  for (const code of ALL_LOCALES) {
    if (['en', 'pt', 'es'].includes(code)) continue;
    const file = join(GEN_DIR, `${code}.ts`);
    generatedCodes.push(code);
    if (existsSync(file)) continue;
    const safe = code.replace('-', '_');
    writeFileSync(
      file,
      [
        '/**',
        ` * ${code} locale — generated stub (untranslated).`,
        ' *',
        ' * Translate the strings and they will be picked up automatically.',
        ' * Missing keys fall back to English at runtime.',
        ' */',
        `const ${safe}: Record<string, string> = {`,
        `  // TODO: translate the ${keyCount} keys from src/lang/en.ts`,
        '};',
        '',
        `export default ${safe};`,
        '',
      ].join('\n'),
    );
    created++;
  }
  // index.ts — static imports so every bundler (rspack/vite) can tree-shake
  const imports = generatedCodes.map((c) => `import ${c.replace('-', '_')} from './${c}';`);
  const map = generatedCodes
    .map((c) => `  '${c}': ${c.replace('-', '_')},`)
    .sort()
    .join('\n');
  writeFileSync(
    join(GEN_DIR, 'index.ts'),
    [
      '/** GENERATED by `npm run gen:locales` — do not edit by hand. */',
      ...imports,
      '',
      'export const generated: Record<string, Record<string, string>> = {',
      map,
      '};',
      '',
    ].join('\n'),
  );
  return created;
}

function cmdCheck() {
  const en = localeKeys(join(LANG_DIR, 'en.ts'));
  let failed = false;
  for (const full of ['pt', 'es']) {
    const keys = localeKeys(join(LANG_DIR, `${full}.ts`));
    const missing = [...en].filter((k) => !keys.has(k));
    const extra = [...keys].filter((k) => !en.has(k));
    if (missing.length || extra.length) {
      failed = true;
      console.error(`✗ ${full}: missing=${missing.length} extra=${extra.length}`);
      if (missing.length) console.error('  missing:', missing.slice(0, 20).join(', '));
      if (extra.length) console.error('  extra:', extra.slice(0, 20).join(', '));
    } else {
      console.log(`✓ ${full}: complete (${en.size} keys)`);
    }
  }
  process.exitCode = failed ? 1 : 0;
}

function cmdMissing(code) {
  const en = localeKeys(join(LANG_DIR, 'en.ts'));
  const file = join(LANG_DIR, `${code}.ts`);
  const keys = existsSync(file) ? localeKeys(file) : new Set();
  const missing = [...en].filter((k) => !keys.has(k));
  console.log(missing.length ? missing.join('\n') : `${code}: complete`);
  process.exitCode = missing.length ? 1 : 0;
}

const args = process.argv.slice(2);
if (args.includes('--check')) {
  cmdCheck();
} else if (args.includes('--missing')) {
  cmdMissing(args[args.indexOf('--missing') + 1]);
} else {
  const created = ensureGenStubs();
  const genFiles = existsSync(GEN_DIR) ? readdirSync(GEN_DIR).filter((f) => f.endsWith('.ts')) : [];
  console.log(`locales: 3 complete (en, pt, es) + ${genFiles.length} generated = ${3 + genFiles.length} total`);
  console.log(`created: ${created} new stub(s) in src/lang/gen/`);
}
